### ISSUE TITLE
Needed a detailed description of the installation of the plugin

### ISSUE THREAD

**Issue by hardsoncore** [trionfo1993/vue-timeline#2]
Could you post a detailed description of the installation of the plugin?
After installation in the project and use:

```
Import VueTimeline from 'vue-timeline';
Vue.use (VueTimeline);
```

I get the error.
Bootstrap set.

**Comment by mizuka-wu** [comment]
it just a component
use it like:
```
<template>
<div><timeline></timeline></div>
</template>

<script>

    import timeline from 'vue-timeline/src/components/timeline.vue'

    export default {
        name: 'score',
        data () {
            return {}
        },
        components: {
            timeline
        }
    }
</script>

<style scoped>
</style>

```

**Comment by hardsoncore** [comment]
Thanks, it worked.

Tell me, is it possible to set the line filling percentage in this component, or are updates planned in this direction?

Like this: 
![1](https://cloud.githubusercontent.com/assets/21140449/26552762/3f5f82fc-4491-11e7-8949-3660ced94ba5.png)

**Comment by mizuka-wu** [comment]
oh, a great idea, i will add it to my plan
